#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h" // ignore the red lines it will dissapear
                      // when roi_cropper.cpp is implemented



// Pull in the static flash memory assets you just generated
#include "image_data.h"
#include "model_data.h"

// Pull in the shared interface contract with Role 1
#include "roi_cropper.h"

static const char *TAG = "PARKING_PREDICTOR";

// Define a structured coordinate layout matching the target parking slots
typedef struct {
    int id;
    int x;
    int y;
    int width;
    int height;
} parking_slot_t;

// Example target zones inside the 640x480 frame space
static const parking_slot_t monitored_slots[] = {
    { .id = 101, .x = 45,  .y = 120, .width = 80, .height = 110 },
    { .id = 102, .x = 140, .y = 115, .width = 75, .height = 115 },
    { .id = 103, .x = 230, .y = 110, .width = 85, .height = 120 }
};

#define TOTAL_SLOTS (sizeof(monitored_slots) / sizeof(parking_slot_t))

// The core pipeline execution task
void parking_pipeline_task(void *pvParameters) {
    ESP_LOGI(TAG, "Initializing Edge ML Pipeline Workspace...");
    
    // We use the _len variable automatically generated by your xxd script
    ESP_LOGI(TAG, "Loaded Quantized Model Size: %d bytes", mobilenet_v2_64x64_quantized_tflite_len);
    
    // Allocate a buffer in internal SRAM for the standardized 64x64 patch
    uint8_t *output_patch_buffer = (uint8_t *)malloc(64 * 64 * sizeof(uint8_t));
    if (output_patch_buffer == NULL) {
        ESP_LOGE(TAG, "Critical Error: Failed to allocate tensor arena space.");
        vTaskDelete(NULL);
    }

    while (1) {
        ESP_LOGI(TAG, "--- Starting Frame Evaluation Sequence ---");
        
        // Loop through each coordinates definition sequentially
        for (int i = 0; i < TOTAL_SLOTS; i++) {
            parking_slot_t slot = monitored_slots[i];
            
            // Execute the contract function owned by Role 1 (The Cropper)
            extract_roi_patch(
                raw_parking_frame, 
                DISPLAY_FRAME_WIDTH, 
                slot.x, slot.y, 
                slot.width, slot.height, 
                output_patch_buffer
            );
            
            // Mock Inference Phase
            // (This will be replaced by the TFLite Micro interpreter later)
            bool is_occupied = (slot.id % 2 == 0); // Simulated toggling for testing
            int mock_confidence = 85 + (slot.id % 15);
            
            // Stream telemetry diagnostics out over UART
            ESP_LOGI(TAG, "Slot ID: %d | Status: %s | Confidence: %d%% [Coordinate Context: X:%d Y:%d]", 
                     slot.id, 
                     is_occupied ? "OCCUPIED" : "VACANT", 
                     mock_confidence,
                     slot.x, slot.y);
        }
        
        ESP_LOGI(TAG, "Frame analysis complete. Staging next sampling interval...");
        
        // Delay the task for 5000 milliseconds (5 seconds) to prevent Watchdog timeouts
        vTaskDelay(pdMS_TO_TICKS(5000));
    }
    
    // Clean up memory if loop ever breaks
    free(output_patch_buffer);
    vTaskDelete(NULL);
}

extern "C" void app_main(void) {
    // Spawn the processing pipeline as a dedicated FreeRTOS task thread
    xTaskCreatePinnedToCore(
        parking_pipeline_task,   // Function task pointer
        "parking_pipeline_task", // Log trace identifier text
        4096,                    // Allocated Stack depth words
        NULL,                    // Execution parameter inputs
        5,                       // Task priority structural tier
        NULL,                    // Task handle tracking instance
        1                        // Core placement affinity allocation (Core 1)
    );
}